name: Focused PHP QA

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  composer:
    uses: sympress/reusable-workflows/.github/workflows/composer-validate.yml@v1

  phpcs:
    uses: sympress/reusable-workflows/.github/workflows/php-coding-standards.yml@v1

  phpstan:
    uses: sympress/reusable-workflows/.github/workflows/php-static-analysis.yml@v1

  phpunit:
    uses: sympress/reusable-workflows/.github/workflows/php-unit.yml@v1
