name: Release

on:
  push:
    branches:
      - main
      - beta
      - alpha

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    uses: sympress/workflows/.github/workflows/automatic-release.yml@177fa0d727b278d2103052ec77c102b4a4c492a0
    with:
      workflow_ref: 177fa0d727b278d2103052ec77c102b4a4c492a0
    secrets:
      GITHUB_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
