name: Monorepo QA

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  qa:
    uses: sympress/reusable-workflows/.github/workflows/sympress-qa.yml@main
    with:
      include_root: true
      package_glob: packages/*
      php_version: '8.5'
