name: Text Quality

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  text-quality:
    uses: sympress/workflows/.github/workflows/text-quality.yml@v1
    with:
      cspell_config: cspell.json
      run_grammar: ${{ github.event_name == 'pull_request' }}
